[package]
name = "generate"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "54.2.0"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
walkdir = "2.5.0"
